### ISSUE TITLE
Station Details like Facilities

### ISSUE THREAD

**Issue by jhoelzl** [jpsingleton/Huxley2#1]
Hi, in the previous version (departureboard.io) a request like this 

`https://api.departureboard.io/api/v2.0/getStationDetailsByCRS/GLC`

returned all station details, like toilets, car park, bicycle park, step-free access.
I could not find anything like this on https://huxley2.azurewebsites.net/.
Is this not available anymore?

Regards,
Josef

**Comment by jpsingleton** [comment]
Huxley (and Huxley 2) have only ever supported Live Departure Board information from [Darwin](https://www.nationalrail.co.uk/100296.aspx). [Knowledgebase (KB)](https://www.nationalrail.co.uk/100298.aspx) content such as station details is not supported.

departureboard.io / Railboard is not affiliated with Huxley 2 so I'm not sure why they redirect to the project. Perhaps as a free alternative when the API was shut down?
