### ISSUE TITLE
Departure board expand option shows previous calling points as null

### ISSUE THREAD

**Issue by crosstracks** [jpsingleton/Huxley2#12]
When I search for a departure board with the expand option enabled, every previousCallingPoints field is null, but subsequentCallingPoints give the expected response. This seems to happen for all trains, regardless of where they start/terminate.

Eg: https://huxley2.azurewebsites.net/departures/sur?expand=true

Could this be an issue with National Rail API? 

Thanks

**Comment by jpsingleton** [comment]
This is a "feature" of the NRE API.

If you use the `all` endpoint you will get both: https://huxley2.azurewebsites.net/all/sur?expand=true
Similarly, the arrivals endpoint _only_ shows `previousCallingPoints`.
