### ISSUE TITLE
Service /service/{Service ID} returns error 500

### ISSUE THREAD

**Issue by jasonkapadia** [jpsingleton/Huxley2#23]
**Describe the bug**
Error 500 in /service/{service id}

**To Reproduce**
Any service ID causes error 500.

**Comment by jpsingleton** [comment]
I'm thinking it's best to rip out all the service ID handling and simply treat it as an arbitrary immutable string that is passed around, otherwise it's cat-and-mouse when NRE inevitably make more breaking changes. Anyone up for doing this?

**Comment by jasonkapadia** [comment]
I can have a go, are you able to let me know the files that these need to be changed in to get /service working?

**Comment by jpsingleton** [comment]
I've made a quick fix and will try to find some time to tidy it up and simplify it. It's working again now though.
