### ISSUE TITLE
Bus and Ferry services are not shown for Staff Departures

### ISSUE THREAD

**Issue by lukeid123** [jpsingleton/Huxley2#5]
When viewing the /staffDepartures/[CRS] endpoint, bus and ferry services are missing with the attribute being null, whereby viewing the normal /departures/[CRS] shows the bus and ferry services. 

![image](https://user-images.githubusercontent.com/54073032/127554481-613393a1-4e10-4acb-9f0d-b65a0a0bf4a5.png)

![image](https://user-images.githubusercontent.com/54073032/127554523-985049fb-49d7-45a7-abbe-295e6540549b.png)

**Comment by jpsingleton** [comment]
This is unfortunately a "feature" of the staff API (https://lite.realtime.nationalrail.co.uk/OpenLDBSVWS/)
>services (string, 1 character): P for train Services, B for bus services, S for ship services. Defaults to "P". Optional.
