### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by davwheat** [jpsingleton/Huxley2#7]
After running this in Docker on my Raspberry Pi for about 3 months straight, I noticed that `htop` was showing memory usage for Huxley2 at 32 GB of memory. Nowhere near that much was in use, but it had 32 GB allocated to it, and accessible.

Obviously, that doesn't seem anywhere near right for what Huxley2 is, and also have no idea where to start looking for issues.

**Comment by jpsingleton** [comment]
I'm afraid this isn't enough information to reproduce your issue. Closing for now.

**Comment by davwheat** [comment]
To reproduce, I purely need to launch Huxley2. There's no other requirements. The virtual ram usage slowly rises to tens of gigabytes.

**Comment by jpsingleton** [comment]
Sorry but that is nowhere near enough information. What version are you running? What version of .NET? What version of Pi and what OS and arch? Debug or release build? Logging level configuration? Does it still happen outside a container? etc. Please have a read of this: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by jpsingleton** [comment]
If you haven't changed the default logging then it could be that. You can try the latest code that reduces default amount of logging.
